name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry + build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-

      - name: Build
        run: cargo build --verbose

      - name: Run tests (if any)
        run: cargo test --all --verbose --no-fail-fast

      - name: Package release binary
        run: cargo build --release

      - name: Upload release binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: keyboim.exe
          path: target/release/keyboim.exe
  release:
    name: Release
    runs-on: windows-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download release binary artifact
        uses: actions/download-artifact@v4
        with:
          name: keyboim.exe
          path: ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: keyboim.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}